### ISSUE TITLE
The main page is 404

### ISSUE THREAD

**Issue by JiaxiangBU** [glicerico/SGNN#7]
glicerico.github.io/sgnn/

**Comment by glicerico** [comment]
Thanks @JiaxiangBU ! It's up now, although the content is not a lot more than the README file XD

**Comment by glicerico** [comment]
Is there something in particular that you would like to know @JiaxiangBU ?

**Comment by JiaxiangBU** [comment]
> Is there something in particular that you would like to know @JiaxiangBU ?

I see, I just want to read the content in the html page built by nbdev. Thanks for your updates.
