### ISSUE TITLE
applying SGNN to conversation data

### ISSUE THREAD

**Issue by SebastianSpeer** [glicerico/SGNN#9]
Dear Andreas,
 
I’m a postdoctoral researcher working in the neuroscience department at Princeton university. I’m currently working on a project related to free form conversations and I was wondering if your CASA algorithm might be useful for the data I have. I our dataset 60 dyads of participants have conversations with each other while their brains are being scanned in an MRI scanner. To talk to each other they are connected via something like zoom and they take turns by pressing a button to pass the mic. My idea was to apply the CASA algorithm trained on the switchboard corpus data to decode dialogue acts from our conversation data. Does that sound reasonable? Do you have any other advice? Perhaps on changing certain parameters?
 
Thanks a lot for your help,
 
Sebastian

**Comment by glicerico** [comment]
Hey Sebastian, it sounds reasonable to use to detect dialogue acts in English. Please note that this implementation is not maintained, hasn't been used much, and that you may need to tweak it yourself.

Also consider other approaches: https://github.com/macabdul9/CASA-Dialogue-Act-Classifier
